"""Generate ``.vscode/settings.json`` for the workspace (run from ``just vscode`` / end of ``just setup``).

The official ``python -m isaaclab --generate-vscode-settings`` does ``import omni.kit_app`` to discover
the Isaac Sim extension search paths, but ``omni.kit_app`` is not importable under a pip-installed
isaacsim (Kit loads it dynamically). So instead we boot a headless ``SimulationApp`` -- the path that
*does* work in both source and pip mode -- and snapshot the extension directories Kit appends to
``sys.path`` during startup, writing them as ``python.analysis.extraPaths`` so Pylance resolves
``omni.*`` / ``isaacsim.*`` / ``isaaclab.*`` imports. Works headless.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

MANAGER_DIR = Path(__file__).resolve().parents[2]


def main() -> None:
    os.environ.setdefault("OMNI_KIT_ACCEPT_EULA", "YES")

    from isaacsim import SimulationApp  # noqa: PLC0415 -- import after the EULA env is set

    # Boot Kit so the extension layout is materialized, then glob the ext dirs Pylance needs (Kit loads
    # most extensions via its own finder, not sys.path, so a sys.path snapshot would miss them).
    app = SimulationApp({"headless": True})
    import isaacsim  # noqa: PLC0415

    isaacsim_path = Path(isaacsim.__file__).resolve().parent
    kit_path = isaacsim_path / "kit"

    ext_dirs: set[str] = set()
    for base in (isaacsim_path, kit_path):
        for sub in ("exts", "extscore", "extscache", "extsDeprecated", "extsUser"):
            d = base / sub
            if d.is_dir():
                ext_dirs.update(str(c) for c in d.iterdir() if c.is_dir())
    kernel_py = kit_path / "kernel" / "py"
    if kernel_py.is_dir():
        ext_dirs.add(str(kernel_py))
    extra_paths = sorted(ext_dirs)

    # NOTE: SimulationApp.close() terminates the process, so write the file *before* closing.
    venv_python = MANAGER_DIR / "ilab" / "bin" / "python"
    settings = {
        "editor.rulers": [120],
        "python.languageServer": "Pylance",
        "python.defaultInterpreterPath": str(venv_python),
        "python.analysis.extraPaths": extra_paths,
        "python.analysis.typeCheckingMode": "basic",
        "python.formatting.provider": "black",
        "python.formatting.blackArgs": ["--line-length", "120"],
        # Index all of resources/ (gitman subrepos, gitignored by the manager) in Ctrl-P / search.
        "search.useIgnoreFiles": False,
        "search.exclude": {
            "**/.git": True, "**/ilab": True, "**/.venv": True, "**/__pycache__": True, "**/*.pyc": True,
            "**/logs": True, "**/wandb": True, "**/outputs": True, "**/.pytest_cache": True,
            "**/*.sif": True, "**/scripts/cluster/exports": True,
        },
        "files.watcherExclude": {
            "**/ilab/**": True, "**/.venv/**": True, "**/.git/**": True, "**/logs/**": True, "**/wandb/**": True,
        },
        # Detect each gitman subrepo under resources/ (depth 2) so SCM shows per-subrepo git status.
        "git.autoRepositoryDetection": True,
        "git.repositoryScanMaxDepth": 3,
        "git.detectSubmodules": False,
    }

    vscode_dir = MANAGER_DIR / ".vscode"
    vscode_dir.mkdir(exist_ok=True)
    settings_path = vscode_dir / "settings.json"
    header = (
        "// Auto-generated by scripts/tools/setup_vscode.py (just vscode). Do not edit by hand;\n"
        "// re-run `just vscode` to refresh the Isaac Sim extension paths.\n"
    )
    settings_path.write_text(header + json.dumps(settings, indent=4) + "\n")
    print(f"[vscode] wrote {settings_path} with {len(extra_paths)} extension paths")

    app.close()


if __name__ == "__main__":
    main()
